server:
  port: 8081

spring:
  profiles:
    active: staging
  banner:
    charset: utf-8
    location: banner.txt
  application:
    name: @project.artifactId@
    version: @project.version@
  main:
    lazy-initialization: true
    web-application-type: servlet